final/photoboard/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pictures do
  	resources :comments
  end

  root "pictures#index"
end

final/photoboard/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :picture
end

final/photoboard/app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_attached_file :image, :styles => { :medium => "300x300>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

final/photoboard/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pictures
end

final/photoboard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

final/photoboard/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@picture = Picture.find(params[:picture_id])

		@comment = @picture.comments.create(params[:comment].permit(:name, :body))
		redirect_to picture_path(@picture)
	end

end

final/photoboard/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@pictures = Picture.all.order("created_at DESC")
	end

	def show
		@picture = Picture.find(params[:id])
	end

	def new
		@picture = current_user.pictures.build
	end

	def create
		@picture = current_user.pictures.build(pic_params)
		if @picture.save
			redirect_to root_path
		end
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
    @picture = Picture.find(params[:id])
    if @picture.update(pic_params)
      redirect_to "/pictures/#{@picture.id}"
    else
      render :edit
    end
	end

	private

	def pic_params
		params.require(:picture).permit(:title, :description, :image)
	end

	def find_picture
		@picture = Picture.find(params[:id])
	end
end

final/photoboard/app/helpers/application_helper.rb
module ApplicationHelper
end

final/photoboard/app/helpers/comments_helper.rb
module CommentsHelper
end

final/photoboard/app/helpers/pictures_helper.rb
module PicturesHelper
end

final/photoboard/app/views/comments/_comment.html.erb
<div>
	<div class="comment_content">
		<p class="comment_name"><strong><u><%= comment.picture.user.email %></u></strong> said: </p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>

	</div>
</div>

final/photoboard/app/views/comments/_form.html.erb
<%= form_for([@picture, @picture.comments.build]) do |f| %>
	<p>
		<%= f.label :content %><br>
		<%= f.text_area :body, :class => 'comment-body' %>
	</p>

	<br>

	<p>
		<%= f.submit %>
	</p>

<% end %>

final/photoboard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photoboard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<ul id="menu-bar">
		<li><%= link_to "Photo Board", root_path %></li>
    <% if user_signed_in? %>
  		<li id="li-new"><%= link_to "Place New", new_picture_path %></li>
  		<li><%= link_to "Account", edit_user_registration_path %></li>
    	<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    <% else %>
    	<li><%= link_to "Sign Up", new_user_registration_path %></li>
    	<li><%= link_to "Log In", new_user_session_path %></li>
    <% end %>
	</ul>

  <%= yield %>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</body>
</html>

final/photoboard/app/views/pictures/_form.html.erb
<div class='form-div'>
	<div class='field'>
	  <%= form.label :Picture %><br>
	  <%= form.file_field :image %>
	  <hr>
	</div>
	<div class='field'>
	  <%= form.label :title %><br>
	  <%= form.text_field :title, :id => 'title' %>
	  <hr>
	</div>
	<div class='field'>
	  <%= form.label :description %><br>
	  <%= form.text_area :description, :id => 'description' %>

	</div>
</div>

final/photoboard/app/views/pictures/edit.html.erb
<%= form_for @picture do |form| %>
	<div class="edit-pic-div">
	  <%= render form %>
	  <div class="actions">
	    <%= form.submit 'Save Changes' %>
	  </div>
	</div>
<% end %>

final/photoboard/app/views/pictures/index.html.erb
<div id="masonry-container" class="transitions-enabled">
	<% @pictures.each do |picture| %>
	<div class="box" id="div-pictures">
	  <a href="/pictures/<%= picture.id %>">
	  	<%= image_tag picture.image.url %>
	  </a>
	  <h2><%= picture.title %></h2>
	</div>
	<% end %>
</div>

final/photoboard/app/views/pictures/new.html.erb
<%= form_for @picture do |form| %>
	<div class="new-pic-div">
	  <%= render form %>
	  <div class="actions">
	    <%= form.submit 'Create Picture!' %>
	  </div>
	</div>
<% end %>

final/photoboard/app/views/pictures/show.html.erb
<div class="one-picture-div">
	<%= image_tag @picture.image.url %>
	<h2><%= @picture.title %></h2>
	<hr class="hr-for-heady">
	<p><%= @picture.description%></p>
	<%= link_to "Edit", edit_picture_path %>
	<%= link_to "Back to Board", pictures_path %>

	<div id="comments">
		<hr class="hr-for-heady">
		<h2><%= @picture.comments.count %> Comments </h2>
		<%= render @picture.comments %>
		<hr class="hr-for-heady">
		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
	</div>
</div>